name = "ArmaForces Medical"
prefix = "afmed"
author = "ArmaForces"
files = [
    "LICENSE",
    "mod.cpp",
    "README.md"
]

exclude = ["*.psd", "*.png", "*.tga"]

modname = "armaforces_medical"
keyname = "armaforces_medical_{{version}}"
signame = "armaforces_medical_{{version}}"

releasebuild = [
    "!Set_version",
    "@zip",
    "!publish"
]

# HEMTT >= 0.7 (unreleased)
#[header_exts]
#version = "{{git \"id 8\"}}"
headerexts = [
    "version={{git \"id 8\"}}"
]

[scripts.Set_version]
    steps_windows = [
        "powershell ./tools/Set-Version.ps1 {{version}} '@armaforces_medical'"
    ]
    # show_output = true

[scripts.publish]
    steps_windows = [
        "powershell ./tools/Publish.ps1 {{version}} YOUR_WORKSHOP_ID '@armaforces_medical'"
    ]
    show_output = true
